### ISSUE TITLE
the issue on the windows

### ISSUE THREAD

**Issue by xiaomengxin123** [wufan-tb/yolo_slowfast#1]
it doesn't work properly on windows, just like this
![image](https://user-images.githubusercontent.com/44745145/147853651-a71848eb-2605-4ffa-8188-9db431d57302.png)
and for many peoples  in a classroom, it doesn't work. just like this
![image](https://user-images.githubusercontent.com/44745145/147865608-eafae022-f0e1-41d2-9e5b-36c5ae9e5173.png)
so I want to the site of its  application scenarios

**Comment by Splending6** [comment]
rm应该是linux的命令 还是别用windows了吧。。

**Comment by wufan-tb** [comment]
rm是linux的命令，但是windows运行后，手动把产生的中间文件夹删掉也可以。
至于第二个问题，理论上人只要能检测出来都可识别行为，这个图片可能属于人没有检测到或者置信度低了。

**Comment by xiaomengxin123** [comment]
> windows 我用 rd /s/q 解决 了那个目录生成的问题，后来发现yolo5模型没有正确加载，在重新下载后，有了一定的效果，但是效果还是不太理想具体如下：
![image](https://user-images.githubusercontent.com/44745145/148321489-6689f6da-e7cc-4fb6-b945-b61329342bd4.png)
![image](https://user-images.githubusercontent.com/44745145/148321590-746ef070-97a1-4cad-bb20-41ecc003a0c5.png)
我想知道影响这些的有哪些因素，按理来说yolo5的检测效果应该不错，但是只是人站立时效果不错，坐着的情况不是那么理想。

**Comment by wufan-tb** [comment]
坐着的有遮挡，可能效果就差点
