### ISSUE TITLE
想问下实时是怎么做的？

### ISSUE THREAD

**Issue by Splending6** [wufan-tb/yolo_slowfast#2]
我用视频测了一下很慢，想问下实时是怎么做的？

**Comment by xiaomengxin123** [comment]
> 
加卡加卡

**Comment by wufan-tb** [comment]
这里使用感觉慢主要是因为需要把视频解析出图片，视频如果比较长的话，提取图片就比较费时间。另外推理batch size越大速度越快，我这边测试30 batchsize可以达到24fps（2080Ti）

**Comment by wufan-tb** [comment]
回头有空在把yolo的输入也改成视频吧

**Comment by Splending6** [comment]
一定得全部提取嘛 摄像头实时好像做不到？我最近在改。。

**Comment by wufan-tb** [comment]
可以不全部提取，提取一个batch处理一次，但是视频流我不太确认能不能支持，这个涉及到pytorchvideo框架的处理方法，针对视频流可能要改不少东西

**Comment by wufan-tb** [comment]
你好，我更新了一个版本，前处理和后处理都优化了，现在整体处理时间基本等于视频时长了。另外你要处理视频流的话也可以在新版本的基础上用两个线程去实现，一个保存一秒视频，一个处理，基本也能达到实时（延时一秒）。

**Comment by nobody-cheng** [comment]
> 你好，我更新了一个版本，前处理和后处理都优化了，现在整体处理时间基本等于视频时长了。另外你要处理视频流的话也可以在新版本的基础上用两个线程去实现，一个保存一秒视频，一个处理，基本也能达到实时（延时一秒）。
不能使用opencv来做视频流处理吗？

**Comment by Bruce-Si** [comment]
> 

请问batchsize在哪改呀，没找到...

**Comment by ekkooee7** [comment]
> 我修改了一个版本，可以跑监控视频流或者PC自带的摄像头，[https://github.com/wangkang12/yolo_slowfast-master，demo_inference_camerweb.py，同时支持Flask](https://github.com/wangkang12/yolo_slowfast-master%EF%BC%8Cdemo_inference_camerweb.py%EF%BC%8C%E5%90%8C%E6%97%B6%E6%94%AF%E6%8C%81Flask) web 端口显示处理的实时画面。

请问这个链接是不是失效了
